Hotfix some code synchronize lost
pmem/kvdk pull request #120
Opened 2021-11-05 07:47 UTC by BaronStack

### What problem does this PR solve?

Problem Summary:
Lost some code when synchronize from local server(Test on local server, maybe change after pull request).

### What is changed and how it works?

Proposal: Lost the return value in kvdk iterator impl.

What's Changed:
Add some boundary code. 

### Check List 

Tests 

- Unit test

Side effects

2021-11-05 08:38 UTC, ZiyanShi requested changes

2021-11-05 08:38 UTC, ZiyanShi commented on examples/graph_sim/src/kv_engines/kvdk.cpp
>    bool Valid() override { iter_->Valid(); }
This one also needs a return value.

2021-11-06 01:53 UTC, BaronStack commented on examples/graph_sim/src/kv_engines/kvdk.cpp
>    bool Valid() override { iter_->Valid(); }
done

2021-11-08 02:58 UTC, KVKIT approved these changes
LGTM

2021-11-09 01:17 UTC, merged