Test: Refactor test cases and add pmem allocator tests
pmem/kvdk pull request #154
Opened 2022-01-10 01:33 UTC by sherry-1001

### What problem does this PR solve?
1. Refactoring test cases
2.  Add pmem allocator tests: correctness and performance.

Tests 

- Unit test
- Integration test
- No code

Side effects
    No

2022-01-10 10:16 UTC, ZiyanShi requested changes

2022-01-10 10:16 UTC, ZiyanShi commented on tests/allocator.hpp
> +        std::chrono::high_resolution_clock::now();
`std::chrono::high_resolution_clock::now()` has an overhead of about 20ns, an unneglectable amount compared to simple operations such as malloc and free, which usually takes several nanoseconds.
Consider do millions of operations and then measure the duration.

2022-01-10 10:16 UTC, ZiyanShi commented on tests/test_pmem_allocator.cpp
> +  }
Test is test. Performance measurement should be put in benchmark.

2022-01-10 10:16 UTC, ZiyanShi commented on tests/test_pmem_allocator.cpp
> +  uint64_t pmem_size = 128ULL << 20; // 32MB
128 MB?

2022-01-10 10:16 UTC, ZiyanShi commented on tests/test_util.h
> +#include "gtest/gtest.h"
necessary?

2022-01-10 10:16 UTC, ZiyanShi commented on tests/tests.cpp
> +    if (type == Types::kSorted) {
Don't k an enum. Just Sorted.
k means constant.

2022-01-25 01:14 UTC, ZiyanShi requested changes

2022-01-25 01:14 UTC, ZiyanShi commented on tests/pmem_allocator_bench.cpp
> +#define NUM_OFFSET 4096
Make these parameters benchmark configs, or use constexpr.
Also, give them a more meaningful name.

2022-01-25 01:14 UTC, ZiyanShi commented on tests/pmem_allocator_bench.cpp
> +DEFINE_uint64(pmem_size, (std::uint64_t)64 << 30, "PMem total size");
(64ULL << 30)
1024ULL

2022-01-25 01:14 UTC, ZiyanShi commented on tests/pmem_allocator_bench.cpp
> +      std::chrono::system_clock::time_point to_begin =
auto

2022-01-25 01:14 UTC, ZiyanShi commented on tests/pmem_allocator_bench.cpp
> +              << iter_num * fixed_alloc_size
Byte?
Second?

2022-01-25 01:14 UTC, ZiyanShi commented on tests/pmem_allocator_bench.cpp
> +    std::srand(seed);
Consider use std::default_random_engine or std::mt19937

2022-01-25 01:14 UTC, ZiyanShi commented on tests/test_pmem_allocator.cpp
> +      thread_manager_.reset(new (std::nothrow) ThreadManager(num_thread));
Let's make things simple.

2022-01-25 01:14 UTC, ZiyanShi commented on tests/test_pmem_allocator.cpp
> +      LaunchNThreads(num_thread, TestPmemAlloc);
Multiple threads with multiple PMEMAllocator?

2022-01-25 01:14 UTC, ZiyanShi commented on tests/test_pmem_allocator.cpp
> +  /* Allocated pmem status (block nums):
What about put all these in a vector and then Allocate according to the vector?

2022-01-25 01:14 UTC, ZiyanShi commented on tests/test_pmem_allocator.cpp
> +  auto TestPmemFrage = [&](uint64_t id) {
Frag?

2022-01-25 01:14 UTC, ZiyanShi commented on tests/test_pmem_allocator.cpp
> +  LaunchNThreads(num_thread, TestPmemFree);
Is it safe to launch multiple Background threads?

2022-01-28 01:34 UTC, sherry-1001 commented on tests/test_pmem_allocator.cpp
> +      LaunchNThreads(num_thread, TestPmemAlloc);
yes

2022-02-21 02:49 UTC, sherry-1001 commented on tests/pmem_allocator_bench.cpp
> +    std::srand(seed);
done.

2022-02-21 02:50 UTC, sherry-1001 commented on tests/pmem_allocator_bench.cpp
> +  static uint64_t get_block_size(uint64_t rand_data) {
Yes, It is actually inverse square distribution. I modified comments.

2022-02-21 03:10 UTC, sherry-1001 commented on tests/allocator.hpp
> +  std::shared_ptr<ThreadManager> thread_manager_;
can't use `unique_ptr`.
![image](https://user-images.githubusercontent.com/7602435/154882931-cf58f687-87c1-4e3f-97fd-3eac377a978f.png)

2022-02-21 05:49 UTC, JiayuZzz commented on tests/allocator.hpp
> +    data.entry = pmem_alloc_->Allocate(alloc_size);
return?

2022-02-21 05:49 UTC, JiayuZzz commented on tests/pmem_allocator_bench.cpp
> +class AllocatorPerformance {
Maybe AllocatorBench or something

2022-02-21 05:49 UTC, ZiyanShi approved these changes

2022-02-21 05:49 UTC, ZiyanShi commented on tests/CMakeLists.txt
> +add_executable(dbbench_pmem_allocator ${BENCH_PMEM_ALLOC})
`add_executable(dbbench_pmem_allocator pmem_allocator_bench.cpp)`

2022-02-21 05:49 UTC, ZiyanShi commented on tests/allocator.hpp
> +#include <stdio.h>
cstdio

seperate external header from kvdk headers

2022-02-21 05:49 UTC, ZiyanShi commented on tests/allocator.hpp
> +  std::shared_ptr<ThreadManager> thread_manager_;
Okay.
But one day we have to use unique_ptr.
Sometimes a write thread will hold the thread manager even when the engine is deleted.

2022-02-21 07:09 UTC, sherry-1001 commented on tests/CMakeLists.txt
> +add_executable(dbbench_pmem_allocator ${BENCH_PMEM_ALLOC})
done

2022-02-21 07:56 UTC, JiayuZzz approved these changes

2022-02-22 06:18 UTC, merged