Test：Add SyncPoint features, Add corner cases, fix some bugs
pmem/kvdk pull request #164
Opened 2022-01-14 08:27 UTC by sherry-1001

### What is changed and how it works?
1. Add `SyncPoint` mechanism in order to check recovery and race condition.
2. Fix BatchWrite and Repair bugs.
3. Add some test corner cases.

Tests 

- Unit test
   test.cpp:  `*SyncPoint*`
- Integration test
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
    - Consumes more PMEM

2022-01-19 09:52 UTC, ZiyanShi commented on tests/tests.cpp
> +      TEST_SYNC_POINT("Test::Set::Start::0");
Please give these Sync Points a meaningful name.
like "Test::before-set-k10v17", "Test::after-set-k8-v15". This can improve readability.

2022-01-19 09:52 UTC, ZiyanShi commented on tests/tests.cpp
> +        [&](void *) { write_batch.store(true); });
Maybe this is some kind of thing that can be done by LoadDependency()?

2022-01-19 09:52 UTC, ZiyanShi commented on engine/kv_engine.cpp
> +  std::vector<Status> statuss(write_batch.Size());
What's this?

2022-01-19 09:52 UTC, ZiyanShi commented on engine/kv_engine.cpp
> +      TEST_SYNC_POINT_CALLBACK("KVEnigne::BatchWrite::BatchWriteRecord", &i);
Like "KVEnigne::BatchWrite::HasPersistedNthKV" ?

2022-01-19 09:52 UTC, ZiyanShi commented on engine/dlinked_list.hpp
> +    TEST_SYNC_POINT("KVEngine::DLinkedList::emplaceBetween::PersistPrev");
"KVEngine::DLinkedList::emplaceBetween::AfterPrevLinkThisBeforeNextLinkThis"
This name is long, but somewhat suitable.

2022-01-19 09:52 UTC, ZiyanShi commented on engine/kv_engine.cpp
> +      TEST_SYNC_POINT("KVEngine::SSetImpl::Update::Finish");
"KVEngine::SSetImpl::AfterUpdate"?

2022-01-19 09:52 UTC, ZiyanShi commented on engine/kv_engine.cpp
> +                           &batch_size);
"AfterAcquireAllSpins"

2022-01-19 09:52 UTC, ZiyanShi commented on engine/kv_engine.cpp
> +    TEST_SYNC_POINT("KVEngine::BatchWrite::Pesistent::0");
"KVEnigne::BatchWrite::BeforePersistNthKV",  consider put it in BatchWrite

2022-01-19 09:52 UTC, ZiyanShi commented on engine/kv_engine.cpp
> +    TEST_SYNC_POINT("KVEngine::StringBatchWriteImpl::HashInsertBefore");
"StringBatchWriteImpl::AfterPersistBeforeInsertInHashTable"

2022-01-19 09:52 UTC, ZiyanShi commented on engine/kv_engine.cpp
> +      TEST_SYNC_POINT("DataEntry::StringDeleteImpl::purgeAndFree");
"StringDeleteImpl::AfterDeletion"
The spin is guarded. There's no way other thread can interrupt next step.

2022-01-19 09:52 UTC, ZiyanShi commented on engine/kv_engine.cpp
> +    TEST_SYNC_POINT("KVEngine::StringSetImpl::PersistBefore");
"StringSetImpl::BeforePersistNewRecord"

2022-01-19 09:52 UTC, ZiyanShi commented on engine/kv_engine.cpp
> +    TEST_SYNC_POINT("KVEngine::StringSetImpl::HashInsertBefore");
"AfterPersistBeforeInsertInHashTable"

2022-01-19 09:52 UTC, ZiyanShi commented on engine/skiplist.cpp
> +    TEST_SYNC_POINT("KVEngine::Skiplist::Insert::CreateNode::Before" +
Let's discuss for a naming standard for all these Sync Points.

2022-01-19 09:57 UTC, ZiyanShi commented on engine/kv_engine.cpp
> +    TEST_SYNC_POINT("KVEngine::StringBatchWriteImpl::HashInsertBefore");
Do we need a Sync Point here? everything is locked?

2022-01-24 03:00 UTC, ZiyanShi approved these changes

2022-01-24 08:16 UTC, ZiyanShi requested changes

2022-01-24 08:16 UTC, ZiyanShi commented on tests/tests.cpp
> +  std::atomic<bool> visited(false);
Is this variable necessary?

2022-01-24 08:16 UTC, ZiyanShi commented on tests/tests.cpp
> +//          A <- C <->D
A<---------D
A<==>C-->D

2022-01-24 08:16 UTC, ZiyanShi commented on tests/tests.cpp
> +
Delete C, crash half way, now the state is ...

2022-01-24 09:02 UTC, ZiyanShi approved these changes

2022-01-25 00:54 UTC, JiayuZzz approved these changes

2022-01-25 01:04 UTC, merged