Persist customized compare function of sorted collection
pmem/kvdk pull request #190
Opened 2022-02-16 06:40 UTC by JiayuZzz

### What problem does this PR solve?

In current impl. customized compare function of sorted collections is not persisted on PMem, so these information will be lost in recovery.

### What is changed and how it works?

- Add a sorted collection configs struct in CreateSortedCollection API to specify compare function and other future configs
- Add functions to encode/decode sorted collection configs to/from a string, persist these string in value of SortedHeaderRecord followed by collection id
- Add comparator to engine configs, so the customized compare functions can be registered before open the engine
- In recovery, decode sorted collection configs from PMem so the customized compare functions can be recovered

### Check List 

Tests 

- Unit test
- Stress test

Side effects

No

2022-02-16 06:52 UTC, ZiyanShi requested changes

2022-02-16 06:52 UTC, ZiyanShi commented on include/kvdk/comparator.hpp
>  class Comparator {
ComparatorTable?

2022-02-16 06:52 UTC, ZiyanShi commented on include/kvdk/comparator.hpp
> +    if (compara_table_.find(name) == compara_table_.end()) {
Should at least warn if user set two comparators with same name.

2022-02-21 03:21 UTC, sherry-1001 commented on engine/kv_engine.hpp
> +                        RecordType collection_type, void* collection_configs);
seems you removed InitCollection define. please removed here, or add its function define, or add TODO comments.

2022-02-21 05:57 UTC, ZiyanShi approved these changes

2022-02-21 05:57 UTC, ZiyanShi commented on engine/skiplist.hpp
> +const ConfigFieldSizeType kEncodedConfigsEndMark = 0;
What's this?

2022-02-21 05:57 UTC, ZiyanShi commented on tests/tests.cpp
> +    configs.log_level = LogLevel::None;
Error, Warn, Verbose

2022-02-21 07:58 UTC, JiayuZzz commented on engine/skiplist.hpp
> +const ConfigFieldSizeType kEncodedConfigsEndMark = 0;
mark the end of a encoded config string

2022-02-21 07:59 UTC, JiayuZzz commented on tests/tests.cpp
> +    configs.log_level = LogLevel::None;
I think current level name is ok

2022-02-21 08:02 UTC, JiayuZzz commented on tests/tests.cpp
> +    configs.log_level = LogLevel::None;
Maybe All is redundant, I removed it

2022-02-22 02:05 UTC, sherry-1001 approved these changes

2022-02-22 05:51 UTC, merged