Engine: Iterating Hash Table
pmem/kvdk pull request #204
Opened 2022-03-07 09:17 UTC by sherry-1001

### What problem does this PR solve?
Add features about iterating hash table.
Scanning hash table using iterator, similarly like STL iterator.  And support range  iterator.
If need to lock slot during iterating hash table, developer can use range iterator.  Please see example in test/tests.cpp: `TestHashTableIterator` case.

Issue Number: [197](https://github.com/pmem/kvdk/issues/197)

Problem Summary:
   Iterating Hash Table is a basic feature for backup and cleaning expired kv, and other functions.

Tests

- Unit test
    `TestHashTableIterator` case
    `TestHashTableRangeIter` case
- Integration test
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
    - Consumes more PMEM

2022-03-08 02:31 UTC, ZiyanShi approved these changes

2022-03-08 02:31 UTC, ZiyanShi commented on engine/kv_engine.hpp
> +  const std::shared_ptr<HashTable> GetHashTable() { return hash_table_; }
Don't expose internal components. Use special macros to expose them for test builds.
Also, no need to return const.

2022-03-08 02:31 UTC, ZiyanShi commented on engine/hash_table.hpp
> +    char* bucket_ptr_;
HashEntry*

2022-03-08 02:31 UTC, ZiyanShi commented on engine/hash_table.hpp
> +      _mm_prefetch(bucket_ptr_, _MM_HINT_T0);
Software prefetches usually does not help.

2022-03-08 09:51 UTC, sherry-1001 commented on engine/hash_table.hpp
> +    char* bucket_ptr_;
can't use hash entry

2022-03-10 01:02 UTC, ZiyanShi requested changes

2022-03-10 01:02 UTC, ZiyanShi commented on engine/hash_table.hpp
> +  bool Invalid() { return header_.index_type == HashIndexType::Invalid; }
Is this used?

2022-03-10 01:02 UTC, ZiyanShi commented on engine/hash_table.hpp
> +  bool Invalid() { return header_.index_type == HashIndexType::Invalid; }
Is this used?

2022-03-11 03:24 UTC, ZiyanShi approved these changes

2022-03-11 07:37 UTC, JiayuZzz approved these changes
LGTM

2022-03-11 07:40 UTC, ZiyanShi approved these changes

2022-03-11 07:40 UTC, ZiyanShi commented on engine/hash_table.hpp
> +    std::unique_lock<SpinMutex> lock_slot{
may dead lock with other operations.
Release iter_lock_slot_ before lock another.

2022-03-18 07:49 UTC, merged