Decouple hash index with sorted collection, and optimize sorted collection rebuilder
pmem/kvdk pull request #208
Opened 2022-03-10 14:30 UTC by JiayuZzz

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

1. Hash index is coupled with skip lists, which is not flexible
2. Sorted collection rebuild do not support non hash indexed skiplist, and has confused logic/poor performance

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

1. Decouple hash index and skip lists, now hash index is optional for a sorted collection, while no hash index, all read and write operations will be indexed by dram nodes
2. Reorganize skip list code
3. Reorganize sorted collection rebuild to support rebuild non-hash-indexed collection, and improve performance & simplify logic 

### Check List 

Tests 

- Unit test
- Stress test
- Benchmark

- Performance
- Compare with original sorted collection, non-hash-indexed one has similar insert performance, update performance is close to insert, read performance drop from 50M to 12M ops
- Parallel skiplist rebuild (now called segment based rebuild) performance improved >10x for 1 collection / 100000 collections in benchmark, and similar for 16~1024 collections

- Future work
- add comments
- release document for sorted collection implementation

2022-03-22 04:19 UTC, ZiyanShi requested changes

2022-03-22 04:27 UTC, JiayuZzz commented on include/kvdk/configs.hpp
> +  int index_with_hashtable = 1;
bool is hard to encode

2022-03-22 04:31 UTC, JiayuZzz commented on engine/skiplist.cpp
> +    SkiplistNode::DeleteNode(node);
resolve this when we have GC mechanism

2022-03-22 04:31 UTC, JiayuZzz commented on engine/skiplist.cpp
>      // result will be invalid, so we need to do double check
we do validate after lock the position

2022-03-22 04:33 UTC, JiayuZzz commented on engine/skiplist.cpp
> +  auto check_id = [&]() {
in fact snapshot is already worked so this may be redundant, just leave it here in case of any accident

2022-03-22 04:36 UTC, JiayuZzz commented on engine/skiplist.cpp
> +  pmem_persist(&new_record->prev, sizeof(PMemOffsetType));
why additional?

2022-03-22 04:40 UTC, JiayuZzz commented on tests/tests.cpp
> +    TestLocalUnorderedCollection("thread_unordered");
sorted collection has different config with unordered collection, so split it to two functions, the behavior of unordered collection is not changed

2022-03-22 04:40 UTC, JiayuZzz commented on engine/skiplist.cpp
> +    prev_record_lock->unlock();
we talked about this already

2022-03-23 10:28 UTC, ZiyanShi commented on engine/sorted_collection/skiplist.cpp
> +  // Check if the linkage has changed before we successfully acquire lock.
Only check linkage is necessary here.

2022-03-23 10:31 UTC, ZiyanShi commented on engine/sorted_collection/skiplist.cpp
> +    return false;
It's possible check_linkage() fail.
Please update your comments.

2022-03-24 01:23 UTC, JiayuZzz commented on tests/tests.cpp
> +  void TestLocalUnorderedCollection(const std::string& collection) {
No rule said a function should be called multiple times, just leave this be until test reorg

2022-03-24 01:25 UTC, JiayuZzz commented on engine/sorted_collection/iterator.hpp
> +      current_ = pmem_allocator_->offset2addr<DLRecord>(current_->next);
It won't. Though these line are redundant,  removed

2022-03-24 02:37 UTC, JiayuZzz commented on engine/sorted_collection/skiplist.cpp
> +      prev_record = next_record;
this resolved by linkage check in the end of write operations

2022-03-24 07:19 UTC, sherry-1001 commented on include/kvdk/configs.hpp
> +  // expired time in milliseconod, should be kPersistTime for no expiration
For set API with `WriteOptions`, the ttl_time is >0, instead of ttl_time is 0.

2022-03-24 07:19 UTC, sherry-1001 commented on tests/tests.cpp
please add restore multi skiplist head test cases.

2022-03-24 07:19 UTC, sherry-1001 commented on engine/sorted_collection/rebuilder.hpp
> +  RebuildResult RebuildIndex();
RebuildDramIndex.

2022-03-24 07:19 UTC, sherry-1001 commented on engine/sorted_collection/skiplist.cpp
> +        pmem_allocator_->offset2addr_checked<DLRecord>(header_record->next);
A problem:   `old_sorted_head`->A
                     `new_sorted_head`<->A
If calling `Destory`,  how correctly purged `old_sorted_head`.  Now seems can't purge `old_sorted_head`.

2022-03-24 07:38 UTC, JiayuZzz commented on engine/kv_engine.cpp
> +      return entry_ptr->GetIndex().skiplist->SetExpiredTime(expired_time);
Already did in kvengine.hpp

2022-03-24 07:40 UTC, JiayuZzz commented on engine/kv_engine.cpp
> +        if (ret.write_record != nullptr) {
If key not exist or already been deleted while call this function

2022-03-24 07:41 UTC, sherry-1001 commented on include/kvdk/configs.hpp
> +  // expired time in milliseconod, should be kPersistTime for no expiration
here ttl_time is 0. I change it in my local.

2022-03-24 08:44 UTC, ZiyanShi requested changes

2022-03-24 08:44 UTC, ZiyanShi commented on engine/kv_engine.cpp
> +  *ttl_time = kInvalidTime;
Let's don't touch things associated with Expire for now. Let Zhichen do them.

2022-03-24 08:44 UTC, ZiyanShi commented on engine/sorted_collection/skiplist.cpp
> +  // After lock:
Please update your comments

2022-03-24 08:44 UTC, ZiyanShi commented on include/kvdk/configs.hpp
> +constexpr int64_t kInvalidTime = -2;
Give constants an appropriate type.
Unix time is different from time period.

2022-03-25 01:47 UTC, ZiyanShi approved these changes

2022-03-25 02:20 UTC, merged