fix warning and background block problem
pmem/kvdk pull request #223
Opened 2022-03-31 02:22 UTC by sherry-1001

Signed-off-by: zhichenj <zhichen.jiang@intel.com>

### What problem does this PR solve?
1. Fix warning about no return type.
2. Workaround to solve block problem for background cleaner.

Tests 

- Unit test
- Integration test
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
    - Consumes more PMEM

2022-03-31 04:13 UTC, ZiyanShi approved these changes

2022-04-01 00:09 UTC, ZiyanShi commented
> Signed-off-by: zhichenj [zhichen.jiang@intel.com](mailto:zhichen.jiang@intel.com)
> 
> ### What problem does this PR solve?
> 1. Fix warning about no return type.
> 2. Workaround to solve block problem for background cleaner.
> 
> Tests
> 
> * Unit test
> * Integration test
> * No code
> 
> Side effects
> 
> * Performance regression
>   
>   * Consumes more CPU
>   * Consumes more MEM
>   * Consumes more PMEM



> Signed-off-by: zhichenj [zhichen.jiang@intel.com](mailto:zhichen.jiang@intel.com)
> 
> ### What problem does this PR solve?
> 1. Fix warning about no return type.
> 2. Workaround to solve block problem for background cleaner.
> 
> Tests
> 
> * Unit test
> * Integration test
> * No code
> 
> Side effects
> 
> * Performance regression
>   
>   * Consumes more CPU
>   * Consumes more MEM
>   * Consumes more PMEM

That's a horrible fix.
A bug fix caused KVDK to consumer more CPU, VMem and PMem?
Take some time to review your PR before actually submit.

2022-04-01 00:09 UTC, ZiyanShi commented
> Signed-off-by: zhichenj [zhichen.jiang@intel.com](mailto:zhichen.jiang@intel.com)
> 
> ### What problem does this PR solve?
> 1. Fix warning about no return type.
> 2. Workaround to solve block problem for background cleaner.
> 
> Tests
> 
> * Unit test
> * Integration test
> * No code
> 
> Side effects
> 
> * Performance regression
>   
>   * Consumes more CPU
>   * Consumes more MEM
>   * Consumes more PMEM



> Signed-off-by: zhichenj [zhichen.jiang@intel.com](mailto:zhichen.jiang@intel.com)
> 
> ### What problem does this PR solve?
> 1. Fix warning about no return type.
> 2. Workaround to solve block problem for background cleaner.
> 
> Tests
> 
> * Unit test
> * Integration test
> * No code
> 
> Side effects
> 
> * Performance regression
>   
>   * Consumes more CPU
>   * Consumes more MEM
>   * Consumes more PMEM

That's a horrible fix.
A bug fix caused KVDK to consumer more CPU, VMem and PMem?
Take some time to review your PR before actually submit.

2022-04-01 00:14 UTC, ZiyanShi requested changes

2022-04-01 00:14 UTC, ZiyanShi commented on engine/kv_engine.cpp
> +  while (!closing_) {
!bg_work_signals_.termination?

2022-04-01 00:14 UTC, ZiyanShi commented on tests/tests.cpp
> +          ASSERT_EQ(INT32_MAX / 10000, ttl_time / 10000);
That's a strange ASSERT_EQ.
`INT32_MAX/10000 > 0 >= ttl_time/10000`

2022-04-01 00:14 UTC, ZiyanShi commented on tests/tests.cpp
> +          ASSERT_EQ(INT32_MAX / 10000, ttl_time / 10000);
That's a strange ASSERT_EQ.
`INT32_MAX/10000 > 0 >= ttl_time/10000`

2022-04-01 05:53 UTC, JiayuZzz commented on engine/kv_engine.cpp
> +  if (!need_clean &&
need_clean_ as private. Or need_global_clean_?

2022-04-01 05:55 UTC, JiayuZzz commented on engine/version/old_records_cleaner.cpp
> +void OldRecordsCleaner::PushToGlabal(
Typo. Glabal -> Global

2022-04-01 05:56 UTC, JiayuZzz approved these changes

2022-04-01 06:33 UTC, ZiyanShi requested changes

2022-04-01 06:33 UTC, ZiyanShi commented on engine/kv_engine.cpp
> +      old_records_cleaner_.PushToGlobal(expired_record_queue);
May be never reached.

2022-04-01 06:33 UTC, ZiyanShi commented on tests/tests.cpp
> +      std::string key = std::to_string(i) + "stringk";
This Status s parameter, is only Status::Ok.

2022-04-01 06:35 UTC, JiayuZzz commented on engine/kv_engine.cpp
> +    }
Put remaining expired records to global

2022-04-01 06:37 UTC, JiayuZzz commented on engine/kv_engine.cpp
> +    }
Put remaining expired records to global

2022-04-01 07:19 UTC, JiayuZzz approved these changes
LGTM

2022-04-01 07:24 UTC, ZiyanShi approved these changes

2022-04-01 07:49 UTC, merged