Refactor access thread, remove limitation on foreground thread and instance number
pmem/kvdk pull request #341
Opened 2022-09-26 06:02 UTC by JiayuZzz

### What problem does this PR solve?

 - Remove limitation on foreground thread and instance number

### What is changed and how it works?

Make thread manager global (singleton) and allocate thread id incrementally, foreground thread access kvdk instance with id % max_access_thread, and acquire lock for synchronization.

### Check List 

Tests 

- Unit test
- Stress test

2022-09-26 06:48 UTC, ZiyanShi requested changes

2022-09-26 06:48 UTC, ZiyanShi commented on engine/kv_engine.hpp
> +    return AccessThreadCV::Holder(&access_thread_cv_[ThreadManager::ThreadID() %
Potential resource leakage. 
1. User set `access_thread_cv_` as 64, then initialize 64 worker threads to call KVDK APIs, which will assign 0-63 to this 64 workers as `id`, 
2. The user join thread with `id` 32 to 63 and initialize another 32 workers, which will be assigned 64-95 as `id`.
3. Threads with `id` as `x` and `x+64` will content with each other for `AccessThreadCV`.

The worst case scenario is when the user initialize and join threads in a pattern that every thread share the same `AccessThreadCV`.

The problem can be partially mitigated by using the old id pool algorithm, or by using a more advanced scheduling algorithm which choose the least used resource, aka, thread id, when initializing a thread.

2022-09-28 03:06 UTC, iyupeng commented on engine/thread_manager.cpp
> +      if (recycle_id_.empty()) {
Should be `!recycle_id_.empty()`?

2022-09-28 03:31 UTC, iyupeng approved these changes

2022-09-28 08:49 UTC, merged